# This is a basic workflow that is manually triggered

name: Run update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update_scores:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.prod.txt
      - name: execute py script # run main.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          mkdir -p ~/.config/gspread/

          echo $GOOGLE_CREDENTIALS > ~/.config/gspread/credentials.json
          python update_sheet.py
